In [35]:
import numpy as np


In [36]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30, 0.7, 1,0,0.5])

In [37]:
def find_abs_mean(y_predicted, y_true):
    sm = 0
    for yp, yt in zip(y_predicted, y_true):
        sm += abs(yt-yp)
    mae = sm/len(y_true)
    return mae

In [38]:
find_abs_mean(y_predicted, y_true)

0.5

In [39]:
def mae_np(y_predicted, y_true):
    return np.mean(abs(y_predicted - y_true))

In [40]:
mae_np(y_predicted, y_true)

0.5

### Implement Log loss

In [41]:
np.log([0,1])

C:\Users\saura\AppData\Local\Temp\ipykernel_13224\1899684472.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0,1])


array([-inf,   0.])

In [42]:
ep = 1e-15

In [43]:
np.log([ep])

array([-34.53877639])

In [44]:
y_pred_new = [max(i, ep) for i in y_predicted]
y_pred_new


[1, 1, 1e-15, 1e-15, 1]

In [45]:
1-ep

0.999999999999999

In [46]:
y_pred_new = [min(i, 1-ep) for i in y_pred_new]
y_pred_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [47]:
y_pred_new = np.array(y_pred_new)

In [48]:
np.log(y_pred_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [49]:
-np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))

17.2696280766844

In [50]:
def log_loss(y_pred, y_true):
    y_pred_new = [max(i, ep) for i in y_pred]
    y_pred_new = [min (i, 1-ep) for i in y_pred_new]
    y_pred_new = np.array(y_pred_new)
    return -np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))

In [51]:
log_loss(y_predicted, y_true)

17.2696280766844

### Mean Squared Error

In [52]:
def mse_wo_np(y_pred, y_tr):
    sqsm = 0
    for pr, tr in zip(y_pred, y_tr):
        sqsm += (pr-tr)**2
    return sqsm/len(y_pred)

In [53]:
mse_wo_np(y_predicted, y_true)

0.366

In [54]:
def mse_w_np(y_pred, y_tr):
    return np.mean(np.square(y_pred - y_tr))

In [55]:
mse_w_np(y_predicted, y_true)

0.366